# vim ft=yaml
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

cache:
  - apt

env:
  global:
    # will be used in the matrix, where neither other variable is used
    - BOTO_CONFIG=/tmp/nowhere
    - DATALAD_TESTS_SSH=1

before_install:
  # for now even remove requirements.txt since dependencies aren't avail
  - echo '' > requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install git-annex-standalone python-dicom python-nipype python-nibabel
  - pip install datalad git+git://github.com/moloney/dcmstack/

install:
  - git config --global user.email "test@travis.land"
  - git config --global user.name "Travis Almighty"

script:
  # - nosetests -s -v --with-doctest --doctest-tests --with-cov --cover-package . --logging-level=INFO tests
  - coverage run `which py.test` -s -v tests

after_success:
  - codecov
